---
version: '2.1'

services:
  annotation-api-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=emannotationapp
      - POSTGRES_USER=emannotationapp
      - POSTGRES_PASSWORD=emannotationapp
    ports:
      - 5444:5432
